#!/usr/bin/env bash
shopt -s nullglob
mkdir image_out
for i in *.jpg *.png *.bmp; do
	new_name=$(echo $i | sed 's/\..*/.jpg/')
	convert                       \
	-strip                        \
	-interlace Plane              \
	-quality 85%                  \
	-sampling-factor 4:2:0        \
	-define jpeg:dct-method=float \
	-resize 800		      \
	"$i"                          \
	image_out/$new_name
done

